name: push to Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker login, Build the image, and push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKUNAME }} -p ${{ secrets.DOCKPASS }}
          docker build -t sreeram91/loginpage -f Dockerfile.dev .
          docker push sreeram91/loginpage
        
